"""Fetch the latest diffusion-model papers from arXiv and append Korean
summaries (generated by Google Gemini, free tier) to README.md.

Runs weekly via .github/workflows/weekly.yml. Requires the GEMINI_API_KEY
environment variable (set as a GitHub Actions secret). Get a free key at
https://aistudio.google.com/apikey (no credit card required).

To switch to a paid provider later (e.g. Anthropic Claude), you only need to
rewrite the `summarize()` function and swap the API-key env var.
"""

import datetime
import os
import sys
import urllib.parse
import urllib.request
import xml.etree.ElementTree as ET

from google import genai

# --- Config ---
README = "README.md"
MARKER = "<!-- LOG -->"
MODEL = "gemini-2.5-flash"  # free-tier model
MAX_PAPERS = 5
# arXiv search query: diffusion models across the main ML/CV/AI categories.
QUERY = (
    'abs:"diffusion model" AND (cat:cs.LG OR cat:cs.CV OR cat:cs.AI OR cat:stat.ML)'
)

ARXIV_NS = {"atom": "http://www.w3.org/2005/Atom"}


def fetch_arxiv(max_results=MAX_PAPERS):
    """Return a list of the most recently submitted diffusion-model papers."""
    params = {
        "search_query": QUERY,
        "sortBy": "submittedDate",
        "sortOrder": "descending",
        "start": 0,
        "max_results": max_results,
    }
    url = "http://export.arxiv.org/api/query?" + urllib.parse.urlencode(params)
    req = urllib.request.Request(url, headers={"User-Agent": "diffusion-paper-log/1.0"})
    with urllib.request.urlopen(req, timeout=60) as resp:
        raw = resp.read()

    root = ET.fromstring(raw)
    papers = []
    for entry in root.findall("atom:entry", ARXIV_NS):
        title = " ".join(entry.findtext("atom:title", "", ARXIV_NS).split())
        abstract = " ".join(entry.findtext("atom:summary", "", ARXIV_NS).split())
        published = entry.findtext("atom:published", "", ARXIV_NS)[:10]
        link = entry.findtext("atom:id", "", ARXIV_NS).strip()
        authors = [
            a.findtext("atom:name", "", ARXIV_NS)
            for a in entry.findall("atom:author", ARXIV_NS)
        ]
        papers.append(
            {
                "title": title,
                "abstract": abstract,
                "published": published,
                "link": link,
                "authors": authors,
            }
        )
    return papers


def summarize(client, paper):
    """Ask Gemini for a concise Korean summary of one paper's abstract."""
    prompt = (
        "다음은 arXiv 디퓨전 모델 논문의 제목과 초록입니다. "
        "한국어로 3~4문장으로 핵심 기여와 방법을 요약해 주세요. "
        "불필요한 수식어 없이 연구자가 빠르게 파악할 수 있게 작성하세요.\n\n"
        f"제목: {paper['title']}\n\n"
        f"초록: {paper['abstract']}"
    )
    resp = client.models.generate_content(model=MODEL, contents=prompt)
    return (resp.text or "").strip()


def format_block(papers, summaries, today):
    lines = [f"## {today} 주간 요약\n"]
    for paper, summary in zip(papers, summaries):
        authors = ", ".join(paper["authors"][:3])
        if len(paper["authors"]) > 3:
            authors += " 외"
        lines.append(f"### [{paper['title']}]({paper['link']})")
        lines.append(f"*{authors} · {paper['published']}*\n")
        lines.append(summary + "\n")
    return "\n".join(lines)


def update_readme(block):
    with open(README, "r", encoding="utf-8") as f:
        content = f.read()
    if MARKER not in content:
        raise SystemExit(f"README.md에 '{MARKER}' 마커가 없습니다.")
    head, tail = content.split(MARKER, 1)
    new = f"{head}{MARKER}\n\n{block}\n{tail.lstrip()}"
    with open(README, "w", encoding="utf-8") as f:
        f.write(new)


def main():
    api_key = os.environ.get("GEMINI_API_KEY")
    if not api_key:
        print("GEMINI_API_KEY 환경 변수가 설정되지 않았습니다.", file=sys.stderr)
        sys.exit(1)

    client = genai.Client(api_key=api_key)
    papers = fetch_arxiv()
    if not papers:
        print("arXiv에서 논문을 찾지 못했습니다.", file=sys.stderr)
        sys.exit(1)

    summaries = [summarize(client, p) for p in papers]
    today = datetime.date.today().isoformat()
    block = format_block(papers, summaries, today)
    update_readme(block)
    print(f"{len(papers)}편의 논문을 README.md에 추가했습니다.")


if __name__ == "__main__":
    main()
